
package lab1;

import lab4.Menu; 

/**
 *
 * @author RizelleAnn
 */
public class SampleUI extends javax.swing.JFrame {
    private static boolean isRerun;
    private static boolean isMainMenu;
    /**
     * Creates new form SampleUI
     */
    public SampleUI() {
        initComponents();
    }
    
    public SampleUI(boolean isRerun, boolean isMainMenu) {
        this.isRerun = isRerun;
        this.isMainMenu = isMainMenu;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        finalWindow = new javax.swing.JDialog();
        finalExitButton = new javax.swing.JButton();
        rerunButton = new javax.swing.JButton();
        bck2MainMenuButton = new javax.swing.JButton();
        thnkULabel = new javax.swing.JLabel();
        simpleRandomButton = new javax.swing.JButton();
        systematicButton = new javax.swing.JButton();
        stratifiedButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        mainMenuTitle = new javax.swing.JLabel();

        finalExitButton.setBackground(new java.awt.Color(0, 0, 0));
        finalExitButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        finalExitButton.setText("Exit");

        rerunButton.setBackground(new java.awt.Color(0, 0, 0));
        rerunButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        rerunButton.setText("Rerun program");
        rerunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rerunButtonActionPerformed(evt);
            }
        });

        bck2MainMenuButton.setBackground(new java.awt.Color(0, 0, 0));
        bck2MainMenuButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        bck2MainMenuButton.setText("Main Menu");

        thnkULabel.setBackground(new java.awt.Color(0, 0, 0));
        thnkULabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        thnkULabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thnkULabel.setText("THANK YOU!");

        javax.swing.GroupLayout finalWindowLayout = new javax.swing.GroupLayout(finalWindow.getContentPane());
        finalWindow.getContentPane().setLayout(finalWindowLayout);
        finalWindowLayout.setHorizontalGroup(
            finalWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finalWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thnkULabel, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, finalWindowLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(finalWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(finalExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bck2MainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rerunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        finalWindowLayout.setVerticalGroup(
            finalWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finalWindowLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(thnkULabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rerunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bck2MainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finalExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setTitle("SAMPLING\n");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(500, 200));
        setName("MainMenu"); // NOI18N

        simpleRandomButton.setBackground(new java.awt.Color(0, 0, 0));
        simpleRandomButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        simpleRandomButton.setForeground(new java.awt.Color(204, 0, 0));
        simpleRandomButton.setText("SIMPLE RANDOM SAMPLING");
        simpleRandomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleRandomButtonActionPerformed(evt);
            }
        });

        systematicButton.setBackground(new java.awt.Color(0, 0, 0));
        systematicButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        systematicButton.setForeground(new java.awt.Color(204, 0, 0));
        systematicButton.setText("SYSTEMATIC SAMPLING");
        systematicButton.setMaximumSize(new java.awt.Dimension(291, 31));
        systematicButton.setMinimumSize(new java.awt.Dimension(291, 31));
        systematicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systematicButtonActionPerformed(evt);
            }
        });

        stratifiedButton.setBackground(new java.awt.Color(0, 0, 0));
        stratifiedButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        stratifiedButton.setForeground(new java.awt.Color(204, 0, 0));
        stratifiedButton.setText("STRATIFIED SAMPLING");
        stratifiedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stratifiedButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(0, 0, 0));
        exitButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(204, 0, 0));
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        mainMenuTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        mainMenuTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuTitle.setText(" BASIC SAMPLING METHODS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(simpleRandomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(systematicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(stratifiedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainMenuTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMenuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(simpleRandomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(systematicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stratifiedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stratifiedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stratifiedButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Strata stratum;
        if(isMainMenu){
            stratum = new Strata(true);
        } else {
            stratum = new Strata(false);
        }
        
        stratum.setVisible(true);
    }//GEN-LAST:event_stratifiedButtonActionPerformed

    private void systematicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systematicButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Input inputWindow;
        if(isMainMenu){
            inputWindow = new Input(2, true);
        } else {
            inputWindow = new Input(2, false);
            
        }
        inputWindow.setVisible(true);
    }//GEN-LAST:event_systematicButtonActionPerformed

    private void simpleRandomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleRandomButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Input inputWindow;
        if(isMainMenu){
            inputWindow = new Input(1, true);
        } else {
            inputWindow = new Input(1, false);
            
        }
        inputWindow.setVisible(true);
    }//GEN-LAST:event_simpleRandomButtonActionPerformed

    private void rerunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rerunButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rerunButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        Menu menu = new Menu();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SampleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SampleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SampleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SampleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SampleUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bck2MainMenuButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton finalExitButton;
    private javax.swing.JDialog finalWindow;
    private javax.swing.JLabel mainMenuTitle;
    private javax.swing.JButton rerunButton;
    private javax.swing.JButton simpleRandomButton;
    private javax.swing.JButton stratifiedButton;
    private javax.swing.JButton systematicButton;
    private javax.swing.JLabel thnkULabel;
    // End of variables declaration//GEN-END:variables
}
