/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab3;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane; 
import lab4.Menu;

/**
 *
 * @author apple
 */
public class Grouped extends javax.swing.JFrame {
    
    int number, type;
    Boolean numberStatus = false, typeStatus = false;
    String title;

    /**
     * Creates new form Grouped
     */
    public Grouped() {
        initComponents();
    }
    
    public Grouped(String title){
        initComponents();
        this.title = title;
        this.setTitle(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numberOfClassIntervals = new javax.swing.JTextField();
        closed_ended = new javax.swing.JRadioButton();
        open_ended = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        editTypeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(400, 70));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Number of Class Intervals:");

        numberOfClassIntervals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfClassIntervalsActionPerformed(evt);
            }
        });
        numberOfClassIntervals.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numberOfClassIntervalsKeyReleased(evt);
            }
        });

        closed_ended.setBackground(new java.awt.Color(51, 51, 51));
        closed_ended.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        closed_ended.setForeground(new java.awt.Color(240, 240, 240));
        closed_ended.setText("Closed-Ended Interval");
        closed_ended.setEnabled(false);
        closed_ended.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closed_endedActionPerformed(evt);
            }
        });

        open_ended.setBackground(new java.awt.Color(51, 51, 51));
        open_ended.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        open_ended.setForeground(new java.awt.Color(240, 240, 240));
        open_ended.setText("Open-Ended Interval");
        open_ended.setEnabled(false);
        open_ended.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_endedActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Select which type of interval to use:");
        jLabel2.setToolTipText("");

        continueButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        continueButton.setText("Continue");
        continueButton.setEnabled(false);
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editButton.setText("EDIT");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        editTypeButton.setText("EDIT");
        editTypeButton.setEnabled(false);
        editTypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTypeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(numberOfClassIntervals, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(closed_ended)
                .addGap(82, 82, 82)
                .addComponent(open_ended)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(240, 240, 240))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(editTypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(305, 305, 305))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(continueButton)
                        .addGap(294, 294, 294))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numberOfClassIntervals, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closed_ended)
                    .addComponent(open_ended))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editTypeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(continueButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberOfClassIntervalsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberOfClassIntervalsKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try{
                int data = Integer.parseInt(numberOfClassIntervals.getText());
                if(data < 5){
                    JOptionPane.showMessageDialog(this, "Input must greater than or equal to 5.", "Error", JOptionPane.ERROR_MESSAGE);
                    numberOfClassIntervals.setText("");
                }else{
                    number = data;
                    numberStatus = true;
                    numberOfClassIntervals.setEnabled(false);
                    closed_ended.setEnabled(true);
                    open_ended.setEnabled(true);
                    editTypeButton.setEnabled(true);
                }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Input must be numeric.", "Error", JOptionPane.ERROR_MESSAGE);
                numberOfClassIntervals.setText("");
            }
        }
    }//GEN-LAST:event_numberOfClassIntervalsKeyReleased

    private void numberOfClassIntervalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfClassIntervalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfClassIntervalsActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        number = 0;
        numberStatus = false;
        numberOfClassIntervals.setText("");
        numberOfClassIntervals.setEnabled(true);
        numberOfClassIntervals.setFocusable(true);
        closed_ended.setEnabled(false);
        open_ended.setEnabled(false);
    }//GEN-LAST:event_editButtonActionPerformed

    private void closed_endedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closed_endedActionPerformed
        type = 1;
        typeStatus = true;
        open_ended.setEnabled(false);
        continueButton.setEnabled(true);
    }//GEN-LAST:event_closed_endedActionPerformed

    private void open_endedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_endedActionPerformed
        type = 2;
        typeStatus = true;
        closed_ended.setEnabled(false);
        continueButton.setEnabled(true);
    }//GEN-LAST:event_open_endedActionPerformed

    private void editTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTypeButtonActionPerformed
        typeStatus = true;
        open_ended.setEnabled(true);
        closed_ended.setEnabled(true);
        open_ended.setSelected(false);
        closed_ended.setSelected(false);
    }//GEN-LAST:event_editTypeButtonActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        if(numberStatus && typeStatus){
            if(type == 1){
                Close_Ended closed = new Close_Ended(number, title);
                this.setVisible(false);
                closed.setVisible(true);
            }else if(type == 2){
                Open_Ended open = new Open_Ended(number, title);
                this.setVisible(false);
                open.setVisible(true);
            }
        }
    }//GEN-LAST:event_continueButtonActionPerformed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        MainMenu menu = new MainMenu();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grouped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grouped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grouped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grouped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grouped().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton closed_ended;
    private javax.swing.JButton continueButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton editTypeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField numberOfClassIntervals;
    private javax.swing.JRadioButton open_ended;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
